package com.omneagate.erbc.Dto;

/**
 * Service messages Enum values
 */
public enum ServiceListenerType {
    ERROR_MSG, REGISTER_USER, LOGIN_USER, PERSONAL_INFO, GETSTATE, GET_DISTRICT, GET_TALUK,
    GET_VILLAGE, SEND_OTP, CONNECTION_INFO, METER_INFO, GET_REGION, GET_SECTION, CHECKVERSION,
    AUTOUPGRADE, GRIEVANCE_CAT, COMPLAINT_SUBMIT, GRIEVANCE_FEEDBACK, PAY_BILL_HISTORY,
    GET_DISTRIBUTION, GET_CONNECTIONCHECK, REG_CONNECTION, REMINDER_ADD, CONSUMER_TYPE, PHASE_TYPE,
    CONNECTION_LIST, CONNECTION_DELETE, CALCUL_METER, BILL_HISTORY, PAY_BILL, PAYMENT_LIST,
    GET_DISCOM, AUTOUPGRADE_ACTIVE, BILL_INFO, COMPLAINT_SUBCAT, GRIEVANCE_LIST,DASHBOARD_GETDETAILS,DASHBOARD_CONNECTIONDETAILS,
    GETGENERATEBILLS,SENDBILLS,GETGRAPHDETAILS,ADDAPPLIANCEBYCONNECTION,GETAPPLIANCEBYCONNECTION,GETCHARGESFORAPPLIANCE,ADDAPPLIANCES,DELETEAPPLIANCES

}

